export {default as AuditDialog} from './auditDialog.vue'
export {default as RecordDialog} from './recordDialog.vue'
export {default as UploadCertificateDialog} from './uploadCertificateDialog.vue'
export {default as ChangeManagerDialog} from './changeManagerDialog.vue'
export {default as ChangeServiceProviderDialog} from './changeServiceProviderDialog.vue'
export {default as RejectDialog} from './rejectDialog.vue'