import Vue from "vue";
import Button from "ant-design-vue/lib/button";
import Steps from "ant-design-vue/lib/steps";
import Form from "ant-design-vue/lib/form";
import Input from "ant-design-vue/lib/input";
import Popover from "ant-design-vue/lib/popover";
import Row from "ant-design-vue/lib/row";
import Col from "ant-design-vue/lib/col";
import Spin from "ant-design-vue/lib/spin";
import Carousel from "ant-design-vue/lib/carousel";
import Icon from "ant-design-vue/lib/icon";
import FormModel from "ant-design-vue/lib/form-model";
import Tag from "ant-design-vue/lib/tag";
import CheckBox from "ant-design-vue/lib/checkbox";
import Radio from "ant-design-vue/lib/radio";
import Select from "ant-design-vue/lib/select";
import TimePicker from "ant-design-vue/lib/time-picker";
import DatePicker from "ant-design-vue/lib/date-picker";
import Space from "ant-design-vue/lib/space";
import InputNumber from "ant-design-vue/lib/input-number";
import ConfigProvider from "ant-design-vue/lib/config-provider";
import Tabs from "ant-design-vue/lib/tabs";
import Progress from "ant-design-vue/lib/progress";
import Anchor from "ant-design-vue/lib/anchor";
import Pagination from "ant-design-vue/lib/pagination";
import Upload from "ant-design-vue/lib/upload";
import Modal from "ant-design-vue/lib/modal";
import message from "ant-design-vue/lib/message";
import Table from "ant-design-vue/lib/table";
import Tooltip from "ant-design-vue/lib/tooltip";
import Dropdown from "ant-design-vue/lib/dropdown";
import Menu from "ant-design-vue/lib/menu";
import MenuItem from "ant-design-vue/lib/menu";
import Alert from "ant-design-vue/lib/alert";
import Collapse from "ant-design-vue/lib/collapse";
import Breadcrumb from "ant-design-vue/lib/breadcrumb";
import Card from "ant-design-vue/lib/card";
import Empty from "ant-design-vue/lib/empty";
import Affix from "ant-design-vue/lib/affix";

message.config({
  maxCount: 1,
});

Vue.prototype.$message = message;
Vue.prototype.$modal = Modal;

Vue.use(Button);
Vue.use(Steps);
Vue.use(Form);
Vue.use(Form.Item);
Vue.use(Input);
Vue.use(Popover);
Vue.use(Row);
Vue.use(Col);
Vue.use(Spin);
Vue.use(Carousel);
Vue.use(Icon);
Vue.use(FormModel);
Vue.use(Tag);
Vue.use(CheckBox);
Vue.use(Radio);
Vue.use(Select);
Vue.use(TimePicker);
Vue.use(DatePicker);
Vue.use(Space);
Vue.use(InputNumber);
Vue.use(ConfigProvider);
Vue.use(Tabs);
Vue.use(Progress);
Vue.use(Anchor);
Vue.use(Pagination);
Vue.use(Upload);
Vue.use(Modal);
Vue.use(message);
Vue.use(Table);
Vue.use(Tooltip);
Vue.use(Dropdown);
Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(Alert);
Vue.use(Collapse);
Vue.use(Breadcrumb);
Vue.use(Card);
Vue.use(Empty);
Vue.use(Affix);
