apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcloud-admin-web
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: xcloud-admin-web
  template:
    metadata:
      labels:
        app: xcloud-admin-web
    spec:
      containers:
        - name: xcloud-admin-web
          image: ${IMAGE}
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: xcloud-admin-web
spec:
  type: ClusterIP
  selector:
    app: xcloud-admin-web
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
